// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbmmeaddhdefxfgtigzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibW1lYWRkaGRlZnhmZ3RpZ3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODQzNjYsImV4cCI6MjA3MzA2MDM2Nn0.QtGObTp0B4-DnZRUv25uyyEgFzX0wRRMfTOHXHk1ia4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});